version: "3"

services:
  server:
    image: zai7lou/rss-reader:latest
    container_name: rss-reader
    restart: unless-stopped
    ports:
      - "19898:8080"
    volumes:
      - "$PWD/config.json:/app/config.json"
      - "$PWD/archives.txt:/app/archives.txt"
